package et.com.Lottery.model;
// Generated Jan 16, 2020 3:36:11 PM by Hibernate Tools 5.2.11.Final


import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * FailedLoginAtempt generated by hbm2java
 */
@Entity
@Table(name="FailedLoginAtempt"

)
public class FailedLoginAtempt implements java.io.Serializable {


     private Long id;
     private long userId;
     private Integer hourlyAtempt;
     private Integer dailyAtempt;
     private Integer totalAtempt;
     private Boolean status;

    public FailedLoginAtempt() {
    }

	
    public FailedLoginAtempt(long userId) {
        this.userId = userId;
    }
    public FailedLoginAtempt(long userId, Integer hourlyAtempt, Integer dailyAtempt, Integer totalAtempt, Boolean status) {
       this.userId = userId;
       this.hourlyAtempt = hourlyAtempt;
       this.dailyAtempt = dailyAtempt;
       this.totalAtempt = totalAtempt;
       this.status = status;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="userId", nullable=false)
    public long getUserId() {
        return this.userId;
    }
    
    public void setUserId(long userId) {
        this.userId = userId;
    }

    
    @Column(name="hourlyAtempt")
    public Integer getHourlyAtempt() {
        return this.hourlyAtempt;
    }
    
    public void setHourlyAtempt(Integer hourlyAtempt) {
        this.hourlyAtempt = hourlyAtempt;
    }

    
    @Column(name="dailyAtempt")
    public Integer getDailyAtempt() {
        return this.dailyAtempt;
    }
    
    public void setDailyAtempt(Integer dailyAtempt) {
        this.dailyAtempt = dailyAtempt;
    }

    
    @Column(name="totalAtempt")
    public Integer getTotalAtempt() {
        return this.totalAtempt;
    }
    
    public void setTotalAtempt(Integer totalAtempt) {
        this.totalAtempt = totalAtempt;
    }

    
    @Column(name="status")
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }




}


