package et.com.Lottery.model;
// Generated Jan 16, 2020 3:36:11 PM by Hibernate Tools 5.2.11.Final


import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * PasswordHistory generated by hbm2java
 */
@Entity
@Table(name="PasswordHistory"

)
public class PasswordHistory implements java.io.Serializable {


     private Long id;
     private String initialPassword;
     private Boolean isPasswordChanged;
     private long userId;

    public PasswordHistory() {
    }

	
    public PasswordHistory(long userId) {
        this.userId = userId;
    }
    public PasswordHistory(String initialPassword, Boolean isPasswordChanged, long userId) {
       this.initialPassword = initialPassword;
       this.isPasswordChanged = isPasswordChanged;
       this.userId = userId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="initialPassword", length=1024)
    public String getInitialPassword() {
        return this.initialPassword;
    }
    
    public void setInitialPassword(String initialPassword) {
        this.initialPassword = initialPassword;
    }

    
    @Column(name="isPasswordChanged")
    public Boolean getIsPasswordChanged() {
        return this.isPasswordChanged;
    }
    
    public void setIsPasswordChanged(Boolean isPasswordChanged) {
        this.isPasswordChanged = isPasswordChanged;
    }

    
    @Column(name="userId", nullable=false)
    public long getUserId() {
        return this.userId;
    }
    
    public void setUserId(long userId) {
        this.userId = userId;
    }




}


